language: node_js
node_js:
- '4'
script: npm run build
deploy:
  provider: s3
  access_key_id: AKIAJWZ725HAYJYEQGHA
  secret_access_key:
    secure: DzqW1oTfTJ91y2BXFRTTpvcbrzVH3tv9F5vOTK3XI/DeRKZc0Z9He/Qd6QskYpG5QK4DX3L9T/0XFOEmf7bKQ9RGA1vDFG8HmkBlE7pJH+4n5I4Wh4XCfvHy9ccv0/48LV3HphI020H7zJnhGSQ6GLl5ceF72J82Dtsi8fwXGzXHBaFLAwaWYwMDY2QWGa7IyuEEQP4Cx1eO/Dyd0KspmVNhV+GVv6MK7+kbpu3YAclgNH741wrx5aNwPjlySkWYHOdtHU/T1AS2pxrcGuEIjvEggu9jT61etilU0g6HkPVMXy+jKRvXiClob2EMN/2jSEXP4R+aWJgJgbJsoqPfIRr6xiy4hlxLSTHdkjr8wk0I+uo/PQ4BUUX6ulfIpf/u5CQ/0IoWyT2zujlhLnU/O920Qwi6/VOO0GFAa56GEVdFutsVxyp1Vn+XhEjqH3k/o/gZHo0iuPK3KgCTGfo7CwVihm8wvO3aPhk05D/wHCxWhMb/aAduxLnylGR5rkBMVv/Hq6SyykDWL0KUnMTcNXAat0lTKElNmU1K5N8xXeGPVO6TeYXYzWOpHEJ1bsHXNtFj3qpnWuYw73T/EEp4oh7av22j2xZAHS99kv1EAm2KSfmY6zBR6j+r269EwBuc7izu9DhnAGaoi54Xd4rIFKcTw1HsJEVv2TfufJj2a7Q=
  bucket: drewschrauf.com
  local-dir: dist
  on:
    tags: true
    repo: drewschrauf/drewschrauf.com
